create DATABASE EMPLOYEE;

USE EMPLOYEE;

/* Create Table*/

CREATE TABLE EMPLOYEE (
    ENAME VARCHAR(50) NOT NULL,
    ESRNO VARCHAR(6) PRIMARY KEY CHECK(LENGTH(ESRNO)=6),
    BDATE DATE,
    ADDRESS VARCHAR(255),
    SEX CHAR(1) DEFAULT('M'),
    SALARY REAL CHECK(SALARY BETWEEN 20000 AND 40000),
    MGRSRNO VARCHAR(6),
    DNO INTEGER,
    FOREIGN KEY (MGRSRNO) REFERENCES Employee(ESRNO)
);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO)
VALUES ('AJIT NAYAK', '133100', '1955-04-25', '73 BOSTON', 'M', 35000, NULL, 1);


INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('SATYA', 495823, '1966-07-17', '26 FINE OAK', 'M', 32770, 133100, 4);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('AJIT BEHERA', 315152, '1971-07-09', '10 KALINGA', 'M', 32802, 133100, 3);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('UMASHANKAR', 216852, '1967-07-17', '26 FINE OAK', 'M', 32770, 133100, 2);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('BHAGWAT', 215152, '1971-03-23', '55 FLORIDA', 'M', 32802, 216852, 2);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('MEENAKSHI', 334548, '1979-04-25', '73 BRIKLY', 'F', 25125, 315152, 3);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('JASWASI', 215485, '1979-08-12', '17 BOSTON', 'M', 20500, 495823, 4);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('NIHAR NAYAK', 334524, '1966-12-17', '73 DALLAS', 'M', 29105, 315152, 3);

INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) 
VALUES ('DEBASMITA', 295485, '1970-04-16', '1 QUEENS LAND', 'F', 20500, 216852, 2);

select * from employee;


CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(12) CHECK(DNAME IN ('RESEARCH', 'ADMIN', 'PROJECT', 'ACADEMIC')),
    DNUMBER INTEGER PRIMARY KEY CHECK(DNUMBER BETWEEN 1 AND 4),
    MGRSRNO VARCHAR(6),
    MGRSTARTD DATE
);


INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSRNO, MGRSTARTD) 
VALUES ('RESEARCH', 4, 495823, '1999-04-20');
INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSRNO,MGRSTARTD) 
VALUES ('ADMIN', 1, 133100,'1988-01-06');
INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSRNO,MGRSTARTD) 
VALUES ('PROJECT', 2, 216852,'1999-07-17');
INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSRNO,MGRSTARTD) 
VALUES ('ACADEMIC', 3, 315152,'1989-12-20');

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INTEGER CHECK(DNUMBER BETWEEN 1 AND 4),
    DLOCATION VARCHAR(12) CHECK(DLOCATION IN ('SINGAPORE', 'INDIA', 'QUUENSLAND', 'LONDON'))
);


INSERT INTO DEPT_LOCATIONS (DNUMBER,DLOCATION) VALUES (2, 'SINGAPORE');
INSERT INTO DEPT_LOCATIONS (DNUMBER,DLOCATION) VALUES (1, 'INDIA' );
INSERT INTO DEPT_LOCATIONS (DNUMBER,DLOCATION) VALUES (4, 'QUUENSLAND' );
INSERT INTO DEPT_LOCATIONS (DNUMBER,DLOCATION) VALUES (3, 'LONDON');

CREATE TABLE PROJECT (
    PNAME VARCHAR(18) CHECK(PNAME IN ('NETWORKING', 'BIO INFORMATICS', 'LINUX')),
    PNUMBER INTEGER PRIMARY KEY,
    PLOCATION VARCHAR(15) CHECK(PLOCATION IN ('KOREA', 'SOUTH AFRICA', 'INDIA')),
    DNUM INTEGER CHECK(DNUM BETWEEN 1 AND 4)
);


INSERT INTO PROJECT (PNAME,PNUMBER,PLOCATION,DNUM) VALUES ('NETWORKING', 11 ,'KOREA', 4);
INSERT INTO PROJECT (PNAME,PNUMBER,PLOCATION,DNUM) VALUES ('BIO INFORMATICS', 19, 'SOUTH AFRICA', 3);
INSERT INTO PROJECT (PNAME,PNUMBER,PLOCATION,DNUM) VALUES ('LINUX', 17, 'INDIA', 2 ); 
 
CREATE TABLE WORKS_ON(
ESRNO VARCHAR(6),
PNO INTEGER(3) CHECK(PNO>0),
HOURS DECIMAL(5,2) CHECK(HOURS>0));

INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (315152, 19, 1.25) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (334548, 19, 3.28) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (215485, 17, 1.25) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (295485, 17, 5.35) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (334548, 19, 2.54) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (295485, 17, 7.2) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (216852, 17, 2.41); 
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (334524, 19, 3.24) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (295485, 17, 1.36) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (495823, 11, 2.36) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (215152, 17, 1.25) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (495823,11, 3.14) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (315152,19, 2.05) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (334548, 19, 2.5) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (495823, 11, 5.27); 
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (215152, 17, 2.32) ;
INSERT INTO WORKS_ON (ESRNO,PNO,HOURS) VALUES (495823, 11, 4.15) ;


/*A)	List the salary of all the employees.  */

SELECT ENAME, SALARY FROM EMPLOYEE;

/*B)	Display the names of all employees with any “A” at any place of the name. */

SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '%A%';
 
/* C) Show all employees who were hired in the first half of the month (Before the 16th of the month).*/

SELECT *
FROM DEPARTMENT
WHERE TO_NUMBER(TO_CHAR(MGRSTARTD, 'DD')) <= 15;

/* D) Display the name of all female employees. */

SELECT ENAME, SEX FROM EMPLOYEE WHERE SEX='F';

/* E) Display the employee who is paid most in the company.*/

SELECT * FROM EMPLOYEE 
WHERE SALARY IN
(SELECT MAX(SALARY)
FROM EMPLOYEE);


/* F) Display employee name, address, department no and department name.*/

SELECT ENAME,ADDRESS,DNO,DNAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.ESRNO=DEPARTMENT.MGRSRNO;

/* G) Display all the employees who are not in ACADEMIC department*/

SELECT EMPLOYEE.ENAME,DEPARTMENT.DNAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON EMPLOYEE.ESRNO = DEPARTMENT.MGRSRNO
WHERE DNAME != 'ACADEMIC';

/* H) Display SATYA’S project location. */

SELECT DISTINCT EMPLOYEE.ENAME, PROJECT.PLOCATION
FROM EMPLOYEE
INNER JOIN WORKS_ON
ON EMPLOYEE.ESRNO = WORKS_ON.ESRNO
INNER JOIN PROJECT ON WORKS_ON.PNO = PROJECT.PNUMBER
WHERE EMPLOYEE.ENAME = 'SATYA';

/* I) Find the total working hours of each female employee.  */

SELECT E.ENAME, SUM(W.HOURS) AS TOTAL_WORKING_HOURS
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.ESRNO = W.ESRNO
WHERE E.SEX = 'F'  
GROUP BY E.ENAME;

/* J) Display the details of the people whose projects are located at SOUTH AFRICA. */

SELECT DISTINCT EMPLOYEE.ENAME, PROJECT.PNAME, PROJECT.PLOCATION, PROJECT.PNUMBER FROM PROJECT
INNER JOIN WORKS_ON ON PROJECT.PNUMBER = WORKS_ON.PNO
INNER JOIN EMPLOYEE ON WORKS_ON.ESRNO = EMPLOYEE.ESRNO
WHERE PROJECT.PLOCATION = 'SOUTH AFRICA'
ORDER BY ENAME;
